# Generated by Django 6.0.2 on 2026-03-04 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('age_bracket', models.CharField(choices=[('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45-54', '45–54'), ('55-64', '55–64'), ('65-74', '65–74'), ('75-84', '75–84'), ('85+', '85+')], max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=5)),
                ('voice', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('none', 'No Voice')], default='male', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='ppst.clinician')),
            ],
        ),
        migrations.CreateModel(
            name='TrialResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.PositiveSmallIntegerField()),
                ('trial_type', models.CharField(choices=[('digit', 'Digit Only'), ('mixed', 'Mixed Digit-Letter')], max_length=10)),
                ('stimulus_sequence', models.CharField(max_length=50)),
                ('patient_response', models.CharField(max_length=50)),
                ('latency_ms', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_responses', to='ppst.testsession')),
            ],
            options={
                'ordering': ['trial_number'],
                'unique_together': {('session', 'trial_number')},
            },
        ),
    ]
