# Generated by Django 4.2.27 on 2026-04-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialresponse',
            name='latencies_ms',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
